# basic options
title: Yaqiong's blog
author: Yaqiong Zhang
email: yaqiong.zhangmse@gmail.com
description: a place for projects, notes, thoughts, ideas ...
github_username: yaqiongz

# Build settings
markdown: kramdown
theme: minima
